

train_columns:
  SeriousDlqin2yrs                     :  int64  
  RevolvingUtilizationOfUnsecuredLines :  float64
  age                                  :  int64  
  NumberOfTime30-59DaysPastDueNotWorse :  int64  
  DebtRatio                            :  float64
  MonthlyIncome                        :  float64
  NumberOfOpenCreditLinesAndLoans      :  int64  
  NumberOfTimes90DaysLate              :  int64  
  NumberRealEstateLoansOrLines         :  int64  
  NumberOfTime60-89DaysPastDueNotWorse :  int64  
  NumberOfDependents                   :  float64

target_column:
  target: SeriousDlqin2yrs

numeric_columns:
  - RevolvingUtilizationOfUnsecuredLines 
  - age                                      
  - NumberOfTime30-59DaysPastDueNotWorse     
  - DebtRatio                              
  - MonthlyIncome                          
  - NumberOfOpenCreditLinesAndLoans          
  - NumberOfTimes90DaysLate                  
  - NumberRealEstateLoansOrLines             
  - NumberOfTime60-89DaysPastDueNotWorse     
  - NumberOfDependents                     
