

train_columns:
  SeriousDlqin2yrs                     :  int64  
  RevolvingUtilizationOfUnsecuredLines :  float64
  age                                  :  int64  
  NumberOfTime30-59DaysPastDueNotWorse :  int64  
  DebtRatio                            :  float64
  MonthlyIncome                        :  float64
  NumberOfOpenCreditLinesAndLoans      :  int64  
  NumberOfTimes90DaysLate              :  int64  
  NumberRealEstateLoansOrLines         :  int64  
  NumberOfTime60-89DaysPastDueNotWorse :  int64  
  NumberOfDependents                   :  float64

target_column:
  target: SeriousDlqin2yrs

numeric_columns:
  - RevolvingUtilizationOfUnsecuredLines 
  - age                                      
  - NumberOfTime30-59DaysPastDueNotWorse     
  - DebtRatio                              
  - MonthlyIncome                          
  - NumberOfOpenCreditLinesAndLoans          
  - NumberOfTimes90DaysLate                  
  - NumberRealEstateLoansOrLines             
  - NumberOfTime60-89DaysPastDueNotWorse     
  - NumberOfDependents                     

fields:
  - name: RevolvingUtilizationOfUnsecuredLines
    min_value: 0.0
    value: 0.0
  - name: age
    min_value: 18
    value: 21
  - name: NumberOfTime30-59DaysPastDueNotWorse
    min_value: 0
    value: 0
  - name: DebtRatio
    min_value: 0.0
    value: 0.0
  - name: MonthlyIncome
    min_value: 20000.0
    value: 50000.0
  - name: NumberOfOpenCreditLinesAndLoans
    min_value: 0
    value: 0
  - name: NumberRealEstateLoansOrLines
    min_value: 0
    value: 0
  - name: NumberOfTime60-89DaysPastDueNotWorse 
    min_value: 0
    value: 0
  - name: NumberOfDependents
    min_value: 0
    value: 0




  
